import React from 'react'
import { Container, Row, Col } from 'react-bootstrap';

const About = () => {
  return (
    <>
        <Container style={{marginTop: '50px'}}>
            <h1>Qui sommes-nous ?</h1>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Explicabo expedita voluptas aut eligendi itaque nostrum nemo, labore aperiam laborum. Eveniet, voluptatem laudantium sapiente quam exercitationem sint corporis enim, eius optio, veniam voluptatibus. Repellat odit iste nemo molestias eligendi culpa rem eius exercitationem atque, recusandae quos accusantium earum ea, excepturi soluta nam. Dolores vero aut voluptatum corporis repudiandae omnis ducimus illum delectus asperiores sint quam nam incidunt blanditiis rerum, commodi harum consequatur vitae repellat totam molestiae necessitatibus possimus, est voluptate. Recusandae quae a alias optio? Ab modi, velit asperiores, est consequuntur architecto libero in cupiditate dicta facilis voluptate dolore illum saepe dignissimos earum ratione explicabo aperiam pariatur, accusantium ut excepturi possimus tempora? Rerum tempore quasi culpa dicta minus porro placeat quo ratione sequi architecto dolorem dolorum inventore eligendi quaerat optio enim consectetur dolores voluptatum adipisci voluptates, facere nihil? Quam veniam quidem suscipit tempora voluptatum amet quod dolores deserunt, dolore maiores ducimus, atque autem. Modi cupiditate eum error vitae placeat sunt voluptate, reprehenderit magnam vero? Mollitia maxime laboriosam aliquam. Et, iure eum. Eum dolorem voluptatum consequatur nesciunt quibusdam autem, quaerat vero odit. Quia vitae laudantium qui, corrupti pariatur porro? Magnam, sunt quaerat eveniet quia quam praesentium neque, repudiandae nisi architecto incidunt adipisci.</p>
            <h1>Notre spécialité</h1>
            <Row>
                <Col md={6}>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam amet nesciunt recusandae magnam maiores cum dicta et quidem officia adipisci. Cupiditate est quisquam excepturi qui facere vel aspernatur molestiae rem maiores deleniti eum esse velit harum enim beatae maxime, porro aut, voluptatibus in incidunt dolore. Nesciunt tempora iusto vitae atque recusandae ad ab repellat possimus ipsa magni? Nulla ab perspiciatis culpa, deleniti obcaecati, quas tempora nemo delectus facilis dolorem voluptatem. Consequatur molestias corrupti praesentium aut. Aliquid voluptates eveniet nobis, mollitia recusandae ex deleniti quod? Enim necessitatibus iusto nulla voluptate, minima quasi iste neque aliquid dolore delectus quos itaque iure accusamus molestiae! Cum omnis, rerum dolorum molestias quaerat facilis nulla nesciunt quibusdam eius tenetur quam quia laboriosam pariatur est. Dignissimos consequuntur esse, itaque harum quos ex voluptates, tenetur perferendis asperiores quaerat odit modi nobis. Perspiciatis minima numquam asperiores id ipsam sit magnam quis neque, iste, eius atque nihil tempore optio esse. Dolorem quod impedit assumenda ratione? Aut et quod deleniti id, incidunt facere quo rerum voluptates excepturi nam illum! Laboriosam doloremque velit blanditiis ad a error! Eius voluptatem, dolore dolorum magnam, ipsum cumque exercitationem dolor sunt deleniti fuga architecto officia reprehenderit laboriosam, nisi esse aut optio adipisci quidem veritatis doloribus illum?</p>
                </Col>
                <Col md={6}>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum corrupti nostrum odio amet quos modi iste, quae veritatis commodi fuga nam quisquam accusantium tempora, eveniet maxime inventore enim. Maxime illo quam velit, deleniti consectetur recusandae quae modi veritatis dolorem doloribus tempora delectus perferendis a sint, nesciunt minima necessitatibus odit quas adipisci laudantium nulla reiciendis vitae. Porro quo voluptatem quis maiores ullam velit doloremque commodi odit! Dolores dolore quasi dolorum debitis ad corporis eos ullam iste qui consectetur molestiae sequi necessitatibus alias incidunt ab, asperiores aspernatur ex quibusdam repudiandae! Vitae adipisci consequatur, distinctio exercitationem reiciendis, nihil id, corporis dolorem impedit natus minima sed ducimus. Fuga quidem ipsum obcaecati nulla enim velit. Tempore sunt natus nulla nam saepe atque voluptates aliquid, aliquam repudiandae, consequuntur eum? Corrupti, minima officiis modi quaerat reiciendis accusantium repudiandae aut. Voluptates libero, veritatis excepturi voluptatem et fugit quam deleniti necessitatibus, officiis sequi unde nemo vel cum ullam laudantium tempora est nostrum quaerat nihil. In laudantium obcaecati, dolorum sed nam quas corrupti a quia repudiandae quibusdam similique amet, vel quod ea eum laboriosam distinctio quaerat cum animi mollitia quidem consectetur ipsam impedit. Sequi dolorum maxime tempora, cupiditate facilis, ex iusto nemo eos iste odit tenetur placeat illum nobis numquam!</p>
                </Col>
            </Row>
            <Row>
                <h1>Le Chef</h1>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque esse nihil deserunt dignissimos recusandae labore sint soluta nisi. Obcaecati officia porro esse consectetur vero animi voluptate! Commodi reiciendis voluptatum, illum autem earum perspiciatis! Illo dolor sunt fugiat, nulla earum aliquid sint soluta quas, totam pariatur, rem reiciendis vitae eius eaque quaerat delectus? Esse ab expedita numquam, deserunt magni in harum aliquid! Similique, illum. Distinctio modi dignissimos repudiandae! Praesentium consectetur labore qui laboriosam unde, dolorem soluta ipsam sapiente quisquam tenetur odit, placeat nobis obcaecati mollitia minima perspiciatis ab error dicta vel. Similique odio quia repudiandae quo eaque, dicta nulla sunt deserunt!</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci expedita a, beatae alias quas iusto ad delectus animi voluptas consequuntur minima. A exercitationem debitis et corporis autem numquam aliquam eius quam, suscipit sapiente rerum sit nam cupiditate. Possimus blanditiis, aspernatur cum accusantium eum provident id aliquid doloribus quasi consequatur alias cumque tempore recusandae! Adipisci similique voluptatum tempora quas, dolore tenetur quo deserunt cupiditate officia, repudiandae et quae! Dignissimos esse aliquam autem dolor perspiciatis nesciunt iusto hic vitae consequuntur odio laudantium quas consequatur earum velit, ad, itaque voluptatum cumque ab eaque tempora? Eligendi voluptas ut aliquid. Nulla ea fuga quae repellat?</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci expedita a, beatae alias quas iusto ad delectus animi voluptas consequuntur minima. A exercitationem debitis et corporis autem numquam aliquam eius quam, suscipit sapiente rerum sit nam cupiditate. Possimus blanditiis, aspernatur cum accusantium eum provident id aliquid doloribus quasi consequatur alias cumque tempore recusandae! Adipisci similique voluptatum tempora quas, dolore tenetur quo deserunt cupiditate officia, repudiandae et quae! Dignissimos esse aliquam autem dolor perspiciatis nesciunt iusto hic vitae consequuntur odio laudantium quas consequatur earum velit, ad, itaque voluptatum cumque ab eaque tempora? Eligendi voluptas ut aliquid. Nulla ea fuga quae repellat?</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci expedita a, beatae alias quas iusto ad delectus animi voluptas consequuntur minima. A exercitationem debitis et corporis autem numquam aliquam eius quam, suscipit sapiente rerum sit nam cupiditate. Possimus blanditiis, aspernatur cum accusantium eum provident id aliquid doloribus quasi consequatur alias cumque tempore recusandae! Adipisci similique voluptatum tempora quas, dolore tenetur quo deserunt cupiditate officia, repudiandae et quae! Dignissimos esse aliquam autem dolor perspiciatis nesciunt iusto hic vitae consequuntur odio laudantium quas consequatur earum velit, ad, itaque voluptatum cumque ab eaque tempora? Eligendi voluptas ut aliquid. Nulla ea fuga quae repellat?</p>
                </Col>
            </Row>
        </Container>
    </>
  )
}

export default About